# In this file, we shall declare all the contants and variables that do not change. 
TEST_URL = "file:///Users/ndtltd/Documents/projects/portifolio/emmanuelmfitumukiza/index.html"
DYNAMIC_DEFAULT_URL = "file:///Users/ndtltd/Documents/projects/portifolio/emmanuelmfitumukiza/"
ABOUT_TEXT = "ABOUT"
PORTFOLIO_DETAILS_TEXT = "Portfolio Details"
PORTFOLIO_TEXT = "PORTFOLIO"
SERVICES_TEXT = "SERVICES"
CONTACT_TEXT = "CONTACT"
HOME_TEXT = "HOME"
ABOUT_URL = DYNAMIC_DEFAULT_URL + "about.html"
PORTFOLIO_DETAILS_URL = DYNAMIC_DEFAULT_URL + "portfolio-details.html"
PORTFOLIO_URL = DYNAMIC_DEFAULT_URL + "portfolio.html"
SERVICES_URL = DYNAMIC_DEFAULT_URL + "services.html"
CONTACT_URL = DYNAMIC_DEFAULT_URL +"contact.html"
HOME_URL = TEST_URL
